In [26]:
import numpy as np

In [27]:
np.__version__

'1.26.4'

In [28]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [29]:
l=[12,52,67,8,3]
l 

[12, 52, 67, 8, 3]

In [30]:
type(l)

list

In [31]:
arr = np.array(l)
arr

array([12, 52, 67,  8,  3])

In [32]:
type(arr)

numpy.ndarray

In [33]:
type(l)

list

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
np.arange(-20, 19)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18])

In [39]:
np.arange(20,10) # first argument must be less then the second argument

array([], dtype=int32)

In [40]:
np.arange(10,30,5) # 3rd argument is used as interval between values

array([10, 15, 20, 25])

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros(10, dtype=int) #hyperparameter tuning is when you change the datatype type of values 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [44]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [46]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [48]:
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

In [49]:
rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
np.random.rand(3,2)

array([[0.48807068, 0.9649831 ],
       [0.23487611, 0.3952803 ],
       [0.01156376, 0.48366172]])

In [ ]:
np.random.rand(3,13)

array([[0.13843751, 0.03995816, 0.86295295, 0.4078327 , 0.98447316,
        0.73688526, 0.47323894, 0.81814046, 0.11903866, 0.56661962,
        0.8978478 , 0.12550211, 0.65024215],
       [0.66344594, 0.68998414, 0.20957584, 0.50263513, 0.95280916,
        0.13456277, 0.66096799, 0.23184991, 0.60481125, 0.46587571,
        0.91742232, 0.33902058, 0.43971192],
       [0.25626807, 0.83318008, 0.47357606, 0.28262595, 0.56013129,
        0.96547912, 0.78981903, 0.74324144, 0.03121527, 0.81560506,
        0.95503715, 0.0680684 , 0.30109854]])

In [ ]:
np.random.randint(3)

0

In [ ]:
np.random.randint(1,10,2)

array([5, 8])

In [ ]:
np.random.randint(1,12,10)

array([ 9,  7,  9,  9,  9, 11,  6,  5,  6,  6])

In [ ]:
np.random.randint(10,40,((10,10)))

array([[18, 19, 20, 21, 34, 37, 24, 28, 14, 17],
       [38, 21, 11, 37, 37, 33, 37, 26, 33, 28],
       [26, 20, 23, 13, 13, 17, 37, 14, 17, 14],
       [23, 21, 19, 25, 33, 33, 33, 17, 23, 22],
       [35, 33, 23, 36, 39, 35, 39, 14, 31, 19],
       [16, 14, 13, 37, 33, 15, 16, 24, 35, 22],
       [26, 18, 10, 14, 36, 20, 35, 14, 22, 21],
       [25, 15, 14, 14, 39, 17, 15, 35, 15, 13],
       [15, 36, 27, 13, 21, 34, 11, 22, 11, 31],
       [17, 26, 14, 39, 12, 34, 15, 16, 10, 14]])

In [ ]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(1,13).reshape(3,4) #reshape() is used to define the size of the matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.arange(1,13).reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(5,4) 
#reshape arguments must be such that the product of reshape arguments must be equal to the total number of elements that can be put ina matrix

ValueError: cannot reshape array of size 12 into shape (5,4)

# slicing

In [ ]:
b = np.random.randint(10,20,(4,5))
b

array([[17, 19, 17, 17, 19],
       [10, 17, 10, 12, 11],
       [12, 16, 18, 15, 16],
       [15, 13, 14, 16, 15]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b

array([[17, 19, 17, 17, 19],
       [10, 17, 10, 12, 11],
       [12, 16, 18, 15, 16],
       [15, 13, 14, 16, 15]])

In [ ]:
b[:]

array([[17, 19, 17, 17, 19],
       [10, 17, 10, 12, 11],
       [12, 16, 18, 15, 16],
       [15, 13, 14, 16, 15]])

In [ ]:
b[1:3] #will print rows only

array([[10, 17, 10, 12, 11],
       [12, 16, 18, 15, 16]])

In [ ]:
b[1,3] # will give one value from the matrix

12

In [ ]:
b[1,-1]

11

In [ ]:
b[2:3]

array([[12, 16, 18, 15, 16]])

In [ ]:
b[0:-2]

array([[17, 19, 17, 17, 19],
       [10, 17, 10, 12, 11]])

In [ ]:
b

array([[17, 19, 17, 17, 19],
       [10, 17, 10, 12, 11],
       [12, 16, 18, 15, 16],
       [15, 13, 14, 16, 15]])

# operations

In [ ]:
a2 = np.random.randint(0,100,(10,10))
a2

array([[52, 90, 91, 67, 86, 49, 19,  1, 74, 11],
       [ 8,  0, 28, 28, 80, 77, 99, 79, 79, 59],
       [54, 39, 98,  7, 75, 80, 23, 61, 50, 19],
       [18,  7, 48, 56, 11, 75, 55, 48, 83, 83],
       [75, 24, 50, 80, 47, 96, 21,  5, 58, 79],
       [85, 21, 35, 48, 49, 58, 79, 57, 87, 27],
       [51, 14, 73, 56, 81, 74, 17, 17, 79, 21],
       [46, 40,  2, 13, 79, 20,  1, 73, 84, 32],
       [31, 84, 33, 53, 87,  1, 54, 96, 96, 60],
       [82, 79, 98, 94, 47,  7, 25, 58, 87, 91]])

In [ ]:
a2[::-2]

array([[82, 79, 98, 94, 47,  7, 25, 58, 87, 91],
       [46, 40,  2, 13, 79, 20,  1, 73, 84, 32],
       [85, 21, 35, 48, 49, 58, 79, 57, 87, 27],
       [18,  7, 48, 56, 11, 75, 55, 48, 83, 83],
       [ 8,  0, 28, 28, 80, 77, 99, 79, 79, 59]])

In [ ]:
a2[::-3]

array([[82, 79, 98, 94, 47,  7, 25, 58, 87, 91],
       [51, 14, 73, 56, 81, 74, 17, 17, 79, 21],
       [18,  7, 48, 56, 11, 75, 55, 48, 83, 83],
       [52, 90, 91, 67, 86, 49, 19,  1, 74, 11]])

In [ ]:
a2[0:10:3]

array([[52, 90, 91, 67, 86, 49, 19,  1, 74, 11],
       [18,  7, 48, 56, 11, 75, 55, 48, 83, 83],
       [51, 14, 73, 56, 81, 74, 17, 17, 79, 21],
       [82, 79, 98, 94, 47,  7, 25, 58, 87, 91]])

In [ ]:
a2.max()

99

In [ ]:
a2.min()

0

In [ ]:
a2.mean()

52.84

# indexing

In [51]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
row = 4
col = 5
col

5

In [53]:
row

4

In [54]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
mat[row,col] # will give the value at the specified row and column

45

In [56]:
mat[4,5]

45

In [57]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
mat[:,5] # will give all the values in the 5th column

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [60]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [61]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [63]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [65]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [66]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[3:-3] # will give all the rows except the first 3 and last 3 rows

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [68]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [70]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [72]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [73]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [74]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [76]:
mat[2:6,2:5] # will give the values from 2nd to 5th row and 2nd to 5th column

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [77]:
mat[1:4, 2:5] # will give the values from 1st to 4th row and 2nd to 5th column

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [78]:
mat[3:8, 2:5] # will give the values from row 3 to 7 and column 2 to 4

array([[32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74]])

# Masking

In [79]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [80]:
id(mat)

2651541344336

In [81]:
mat<50 # will give a boolean matrix where the values are True if the value is less than 50 and False otherwise

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [82]:
mat>50 # will give a boolean matrix where the values are True if the value is greater than 50 and False otherwise

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [83]:
mat == 50 # will give a boolean matrix where the values are True if the value is equal to 50 and False otherwise

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [84]:
mat[mat == 50] # will give the values that are equal to 50

array([50])

In [86]:
x = mat[mat < 50] # will give the values that are less than 50
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [87]:
y = mat[mat > 50] # will give the values that are greater than 50
y

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [88]:
a = mat[mat <= 50] # will give the values that are less than or equal to 50
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])